# 002
# https: // projecteuler.net/problem = 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


n0 = 1
n1 = 2
fibValue = 0
evenValuedSum = 2

while True:
    fibValue = n0 + n1

    if fibValue % 2 == 0:
        evenValuedSum += fibValue

    n0 = n1
    n1 = fibValue

    if(fibValue > 4000000):
        break

print(evenValuedSum)